version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    environment:
      - DEFAULT_HOST=127.0.0.1.xip.io
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx0:
    image: nginx
    volumes:
      - ./nginx0_html:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=127.0.0.1.xip.io

  nginx1:
    image: nginx
    volumes:
      - ./nginx1_html:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=nginx1.127.0.0.1.xip.io
  
  nginx2:
    image: nginx
    volumes:
      - ./nginx2_html:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=nginx2.127.0.0.1.xip.io
