version: '2'

networks:
  proxy:
    driver: bridge

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    environment:
      - DEFAULT_HOST=127.0.0.1.xip.io
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx0:
    image: nginx
    volumes:
      - ../www/default:/usr/share/nginx/html
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=127.0.0.1.xip.io
