version: '3.0'

services:
  nginx1:
    image: nginx
    volumes:
      - ../../www/html1:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=nginx1.127.0.0.1.xip.io
    networks:
      - frontend

networks:
  frontend:
    external:
      name: nginx-proxy-adv_proxy
